#!/bin/bash
#
# atse-find-provides
#-----------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License. You may
# obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.
#-----------------------------------------------------------------------

IFS=$'\n'

# Get the list of files.
filelist=`sed "s/[]['\"*?{}]/\\\\\&/g"`

# Perl modules: append an additional (atse) color delimiter
if [ -x /usr/lib/rpm/perl.prov -a -n "$filelist" ];then
    provideList=$(echo $filelist | tr '[:blank:]' \\n | grep '\.pm$' | /usr/lib/rpm/perl.prov | sort -u)
    for provide in $provideList; do
        # Provide is either something like "perl(Error)" or "perl(Error) =  0.17025"
        # To work in both cases, use sed to key off the ')' and change to ')(atse)'
        echo $(echo $provide | sed "s/)/)(atse)/")
    done
fi
